version: '3.8'
services:
  huggingface_model:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      - HUGGING_FACE_HUB_TOKEN=<secret>
    ports:
      - 5555:8000
    ipc: host
    command: --model microsoft/Phi-3.5-mini-instruct

